### ISSUE TITLE
TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by little-petrol** [binance/binance-connector-python#115]
### Issue subject
This code would raise the error.
```python
from binance.spot import Spot
client2 = Spot(key='...', secret='...')
print(client2.ticker_price())
```
but use testnet is OK.
```python
client2 = Spot(base_url='https://testnet.binance.vision',
               key='...',
               secret='...')
print(client2.ticker_price())
```
and I can get all price using Chrome -> https://api.binance.com/api/v3/ticker/price
but not `Spot` in Pycharm
### Expected behaviour
D:\Anaconda\python.exe E:/PythonProjects/BinanceArbitrage/main.py
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "D:\Anaconda\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C47AA92070>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C47AA92070>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/PythonProjects/BinanceArbitrage/main.py", line 11, in <module>
    print(client2.ticker_price())
  File "D:\Anaconda\lib\site-packages\binance\spot\market.py", line 205, in ticker_price
    return self.query("/api/v3/ticker/price", params)
  File "D:\Anaconda\lib\site-packages\binance\api.py", line 68, in query
    return self.send_request("GET", url_path, payload=payload)
  File "D:\Anaconda\lib\site-packages\binance\api.py", line 115, in send_request
    response = self._dispatch_request(http_method)(**params)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C47AA92070>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Process finished with exit code 1

### Environment
Provide any relevant information about your setup, such as:
Version of binance-connector-python lastest
Python version 3.8
Operating system win10
IDE Pycharm

**Comment by chairz** [comment]
https://dev.binance.vision/t/cant-connect-using-official-sdk-please-help-to-see/7370

Are you connected to vpn?  you can add proxy when initializing the client object. Refer to link above.

**Comment by aisling11** [comment]
Hi @little-petrol, closing this issue due to inactivity after suggesting use of the proxy feature for the retest. However, feel free to reopen this if further discussion is needed.
