### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by processdatatech** [binance/binance-connector-python#127]
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/tls.py", line 296, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/policies.py", line 110, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1207, in _dataReceived
    self.consumeData()
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1219, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1579, in processData
    fr = self.onFrameEnd()
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1704, in onFrameEnd
    self._onMessageEnd()
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 318, in _onMessageEnd
    self.onMessageEnd()
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 321, in _onMessage
    self.onMessage(payload, isBinary)
  File "/usr/local/lib/python3.6/site-packages/binance/websocket/binance_client_protocol.py", line 31, in onMessage
    self.factory.callback(payload_obj)
  File "/root/download/work/coin/trade_strg_03.py", line 218, in message_handler
    track.dataSubscribe(message.get('k')['s'],closeP,track.trade,highP)
  File "/root/download/work/coin/trade_strg_03.py", line 190, in dataSubscribe
    self.strategy.strategy(price,self,trade,highPrice)
  File "/root/download/work/coin/trade_strg_03.py", line 75, in strategy
    response = trade.tradeClient.new_order(**params)
  File "/usr/local/lib/python3.6/site-packages/binance/spot/account.py", line 66, in new_order
    return self.sign_request("POST", url_path, params)
  File "/usr/local/lib/python3.6/site-packages/binance/api.py", line 83, in sign_request
    return self.send_request(http_method, url_path, payload)
  File "/usr/local/lib/python3.6/site-packages/binance/api.py", line 117, in send_request
    self._handle_exception(response)
  File "/usr/local/lib/python3.6/site-packages/binance/api.py", line 170, in _handle_exception
    raise ClientError(status_code, err["code"], err["msg"], response.headers)
binance.error.ClientError: (400, -1013, 'Filter failure: LOT_SIZE', {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '47', 'Connection': 'keep-alive', 'Date': 'Sun, 27 Mar 2022 02:27:44 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'e7b3bf5d-c3f0-4466-8ddf-448206cf16b5', 'x-mbx-used-weight': '57', 'x-mbx-used-weight-1m': '57', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 6806abb26fb4ce0aa6ebca12d6a79246.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YTO50-C2', 'X-Amz-Cf-Id': 'oCnC15UMcODtHicYpNDobBbxntmqWb1qI37zDusM03H8GcuDW36APA=='})

WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake), code: 1006, clean: False, reason: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
Lost connection to Server. Reason: [Failure instance: Traceback: <class 'binance.error.ClientError'>: (400, -1013, 'Filter failure: LOT_SIZE', {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '47', 'Connection': 'keep-alive', 'Date': 'Sun, 27 Mar 2022 02:27:44 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'e7b3bf5d-c3f0-4466-8ddf-448206cf16b5', 'x-mbx-used-weight': '57', 'x-mbx-used-weight-1m': '57', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 6806abb26fb4ce0aa6ebca12d6a79246.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YTO50-C2', 'X-Amz-Cf-Id': 'oCnC15UMcODtHicYpNDobBbxntmqWb1qI37zDusM03H8GcuDW36APA=='})
/usr/local/lib/python3.6/site-packages/twisted/python/log.py:80:callWithContext
/usr/local/lib/python3.6/site-packages/twisted/python/context.py:117:callWithContext
/usr/local/lib/python3.6/site-packages/twisted/python/context.py:82:callWithContext
/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py:696:_doReadOrWrite
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py:683:_doReadOrWrite
/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py:248:doRead
/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py:253:_dataReceived
/usr/local/lib/python3.6/site-packages/twisted/protocols/tls.py:330:dataReceived
/usr/local/lib/python3.6/site-packages/twisted/protocols/tls.py:296:_flushReceiveBIO
/usr/local/lib/python3.6/site-packages/twisted/protocols/policies.py:110:dataReceived
/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py:290:dataReceived
/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py:1207:_dataReceived
/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py:1219:consumeData
/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py:1579:processData
/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py:1704:onFrameEnd
/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py:318:_onMessageEnd
/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py:628:onMessageEnd
/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py:321:_onMessage
/usr/local/lib/python3.6/site-packages/binance/websocket/binance_client_protocol.py:31:onMessage
/root/download/work/coin/trade_strg_03.py:218:message_handler
/root/download/work/coin/trade_strg_03.py:190:dataSubscribe
/root/download/work/coin/trade_strg_03.py:75:strategy
/usr/local/lib/python3.6/site-packages/binance/spot/account.py:66:new_order
/usr/local/lib/python3.6/site-packages/binance/api.py:83:sign_request
/usr/local/lib/python3.6/site-packages/binance/api.py:117:send_request
/usr/local/lib/python3.6/site-packages/binance/api.py:170:_handle_exception
]. Retrying: 1

**Comment by chairz** [comment]
binance.error.ClientError: (400, -1013, 'Filter failure: LOT_SIZE', {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '47', 'Connection': 'keep-alive', 'Date': 'Sun, 27 Mar 2022 02:27:44 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'e7b3bf5d-c3f0-4466-8ddf-448206cf16b5', 'x-mbx-used-weight': '57', 'x-mbx-used-weight-1m': '57', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 6806abb26fb4ce0aa6ebca12d6a79246.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YTO50-C2', 'X-Amz-Cf-Id': 'oCnC15UMcODtHicYpNDobBbxntmqWb1qI37zDusM03H8GcuDW36APA=='})

There is a LOT_SIZE error meaning that your quantity's decimal places are more than the allowed decimal places. You can check LOT_SIZE under the exchangeInfo endpoint.

**Comment by 2pd** [comment]
this error `binance.error.ClientError` is thrown from this library by design.

Users are recommended to handle the exception in their application.
