### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by keven023** [binance/binance-connector-python#195]
hey brother 
 i download ur zip and "https://github.com/binance
/
[binance-connector-python](https://github.com/binance/binance-connector-python)"
and wheni creat py folder and copie this "
from binance.spot import Spot

client = Spot()

# Get server timestamp
print(client.time())
# Get klines of BTCUSDT at 1m interval
print(client.klines("BTCUSDT", "1m"))
# Get last 10 klines of BNBUSDT at 1h interval
print(client.klines("BNBUSDT", "1h", limit=10))" from your exemple i get this error 

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\binance-connector-python-master\binance-connector-python-master\oroginal Copie.py", line 1, in <module>
    from binance.spot import Spot
  File "c:\Users\Admin\Desktop\binance-connector-python-master\binance-connector-python-master\binance\spot\__init__.py", line 1, in <module>
    from binance.api import API
  File "c:\Users\Admin\Desktop\binance-connector-python-master\binance-connector-python-master\binance\api.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

i didnt know what to do

**Comment by tungrix** [comment]
Have you installed `requests`module?
If not, please follow [How to Install Requests Library in Python](https://www.agiratech.com/install-requests-library-in-python).

**Comment by keven023** [comment]
yes i did it dude i dont know why he said no module but i already have the
package look these 2 pic [image: Capture d’écran 2022-12-21 100158.png][image:
Capture d’écran 2022-12-21 100122.png]

**Comment by tungrix** [comment]
The images are not available.

**Comment by keven023** [comment]
![Capture d’écran 2022-12-21 100122](https://user-images.githubusercontent.com/121122161/208889010-8fe6e130-fec2-4a30-8386-05c77d8573ad.png)
![Capture d’écran 2022-12-21 100158](https://user-images.githubusercontent.com/121122161/208889036-9bb5e656-2295-448a-8af7-f70674e54163.png)

**Comment by keven023** [comment]
help me plzzz :'(

**Comment by keven023** [comment]
bro i fix it by using another edi i use pycharm and fix the modules but after all that i get this massage !! 
![6](https://user-images.githubusercontent.com/121122161/208958103-514fca55-4ba6-41ae-a762-4a681d792017.png)
from the beggning he ask for api then when i put it he said ivalid api key 
![5](https://user-images.githubusercontent.com/121122161/208958527-31300689-a1c6-42e9-862e-f5d2047837d9.png)

**Comment by tungrix** [comment]
By calling `print(client.account())`, you are trying to fetch the data related to your account, so a valid api key and secret are necessary.

**Comment by keven023** [comment]
<3 <3 <3 i make it ty for help now i have another pb hahah but i will try buy myself and if ififnt get a sultion i will back to help me (not i m noob in info but i did my beast to learn hahah thanks again bro /sis <3)

**Comment by 2pd** [comment]
Looks like it is not an issue.
