### ISSUE TITLE
SpotWebsocketAPIClient Timeout instantly -> 1 to 10 seconds

### ISSUE THREAD

**Issue by souchy99** [binance/binance-connector-python#273]
The problem, is that once I open the websocket (used for transactions purpose) it timeout each time after let's say a few seconds. Wich make it non possible to use it properly. 

### Expected behaviour
I would like it  to run for at least few hours, even a loss in that case can be handled with a simple try ecept schem

### Actual behaviour
The stream work because i'm able to send an order but, the call back works too because I get the result frame. But a timeout occur systematicly after te transaction wich is problematic.

### Steps to reproduce
Here is the code used the full 
(except for api key/secret) 

`from binance.websocket.spot.websocket_api import SpotWebsocketAPIClient
import time
class BinanceAccount:
    def __init__(self,callback_function):
        self.orders = {}#list of orders kept updated (by order id)
        self.spot_owned = {}
        self.client = SpotWebsocketAPIClient(on_message=callback_function,api_key='yyyyyyyyyyyyyyyyy',api_secret='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

    def postOrder(self,symbol: str,side,type,quantity,price):
        return self.client.new_order(symbol=symbol,side=side,type=type,quantity=quantity,price=price,newOrderRespType="FULL")
    
    def cancelOrder(self,orderID,symbol):
        return self.client.cancel_order(symbol=symbol,orderId=orderID)
    
    def replaceOrder(self,orderID,symbol,mode,side,type,qty,price):
        return self.client.cancel_replace_order(cancelOrderId=orderID,symbol=symbol,cancelReplaceMode=mode,side=side,type=type,quantity=qty,price=price,newOrderRespType="FULL")

    def getCurrentOrders(self):
        return self.client.get_open_orders()
    
    def getSpotOwned(self):
        return self.client.account()
    
    def closeConnexion(self):
        print("BinanceAccount - Closing the websocket api connection")
        self.client.stop()

def callback(_,message):
    print(message)

acc = BinanceAccount(callback)
acc.postOrder("BTCUSDT","BUY","LIMIT_MAKER",0.0003,30000)
time.sleep(30)
acc.closeConnexion()

`

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python 3.1
* Python version 3.12.0
* Operating system windows 10 family

**Comment by souchy99** [comment]
`Websocket connection timeout
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_socket.py", line 110, in recv      
    bytes_ = _recv()
             ^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_socket.py", line 89, in _recv      
    return sock.recv(bufsize)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1234, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1107, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\binance\websocket\binance_socket_manager.py", 
line 60, in run
    self.read_data()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\binance\websocket\binance_socket_manager.py", 
line 81, in read_data
    raise e
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\binance\websocket\binance_socket_manager.py", 
line 73, in read_data
    op_code, frame = self.ws.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_core.py", line 408, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_core.py", line 447, in recv_frame  
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_abnf.py", line 340, in recv_frame  
    self.recv_header()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_abnf.py", line 296, in recv_header 
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_abnf.py", line 375, in recv_strict 
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_core.py", line 531, in _recv       
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\websocket\_socket.py", line 112, in recv      
    raise WebSocketTimeoutException("Connection timed out")
websocket._exceptions.WebSocketTimeoutException: Connection timed out`

**Comment by fgplastina** [comment]
I'm getting the same result. Can't even get an stable connection.

**Comment by p-nawotczynski** [comment]
Same for me on Python 3.10

**Comment by souchy99** [comment]
Yes, fixed too, the same way, I put timeout = 200, In did this is not a bug just a config issue. This is just the amount of seconds the program will wait for a new response to a request on the api. So if you don't do a lot of requests None is a good way as you said. In my case 200 is enough since i build HTF bot
