### ISSUE TITLE
安装binance-futures-connector后，websocket client不能运行

### ISSUE THREAD

**Issue by roc1** [binance/binance-connector-python#324]
重现：
1、
先安装最新版（3.7.0）binance-connector-python
2、
再安装最新版（4.0.0）binance-futures-connector
3、
执行代码：
`# WebSocket Stream Client
from binance.websocket.spot.websocket_stream import SpotWebsocketStreamClient

def message_handler(_, message):
    logging.info(message)

proxies = { 'http': 'http://1.2.3.4:8080' }

my_client = SpotWebsocketStreamClient(on_message=message_handler, proxies=proxies, timeout=10)

# Subscribe to a single symbol stream
my_client.agg_trade(symbol="bnbusdt")
time.sleep(5)
logging.info("closing ws connection")
my_client.stop()`

报错：
`Traceback (most recent call last):
  File "E:\xx.py", line 10, in <module>
    from binance.websocket.spot.websocket_api import SpotWebsocketAPIClient
  File "E:\xxx\venv\Lib\site-packages\binance\websocket\spot\websocket_api\__init__.py", line 6, in <module>
    class SpotWebsocketAPIClient(BinanceWebsocketClient):
  File "E:\xxx\venv\Lib\site-packages\binance\websocket\spot\websocket_api\__init__.py", line 39, in SpotWebsocketAPIClient
    from binance.websocket.spot.websocket_api._market import ping_connectivity
  File "E:\xxx\venv\Lib\site-packages\binance\websocket\spot\websocket_api\_market.py", line 1, in <module>
    from binance.lib.utils import get_uuid, purge_map
ImportError: cannot import name 'get_uuid' from 'binance.lib.utils' (E:\xxx\venv\Lib\site-packages\binance\lib\utils.py)
`

似乎是futures库把utils.py 覆盖了？

**Comment by chris-anjost** [comment]
The problem is that both dependencies share the same package name i.e. binance.

A quick fix is to change the order of installation:

1. Remove both packages
2. Install binance-futures-connector
3. Install binance-connector

**Comment by alplabin** [comment]
Hi @roc1 , I'm closing this issue as we published a brand new modularised version of the Python connector. Feel free to start using it and open a new issue if you encounter any problems.
