### ISSUE TITLE
ERR access the value of each element Dictionary

### ISSUE THREAD

**Issue by kp0987654321** [binance/binance-connector-python#350]
python3.13 , binance-connector  3.10.0
myscript:
#!/usr/local/bin/python
import json
import logging
import time
from binance.lib.utils import config_logging
from binance.websocket.spot.websocket_stream import SpotWebsocketStreamClient

config_logging(logging, logging.DEBUG)

def message_handler(_, message):
    json_message = json.loads(message)
    print(message)
    print(type(message)) 
    print(json_message['stream'])
my_client = SpotWebsocketStreamClient(on_message=message_handler, is_combined=True)

my_client.subscribe(
    stream=["jupusdt@kline_1m", "btcusdt@kline_1m"],
)

script worked well if without codeline :  print(json_message['stream'])
script not working with codeline :  print(json_message['stream'])

ERR: 

2024-12-12 08:02:44.972 UTC DEBUG binance.websocket.websocket_client: Creating connection with WebSocket Server: wss://stream.binance.com:9443/stream, proxies: {}
2024-12-12 08:02:44.986 UTC DEBUG binance.websocket.websocket_client: WebSocket connection has been established: wss://stream.binance.com:9443/stream, proxies: {}
2024-12-12 08:02:44.986 UTC DEBUG binance.websocket.websocket_client: Binance WebSocket Client started.
2024-12-12 08:02:44.987 UTC DEBUG binance.websocket.websocket_client: Sending message to Binance WebSocket Server: {"method": "SUBSCRIBE", "params": ["jupusdt@kline_1m", "btcusdt@kline_1m"], "id": 1733990564986}
{"result":null,"id":1733990564986}
<class 'str'>
2024-12-12 08:02:45.138 UTC ERROR binance.websocket.websocket_client: Error from callback <function message_handler at 0x7fcb4786f100>: 'stream'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/binance/websocket/binance_socket_manager.py", line 60, in run
    self.read_data()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/binance/websocket/binance_socket_manager.py", line 88, in read_data
    self._handle_data(op_code, frame, data)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/binance/websocket/binance_socket_manager.py", line 110, in _handle_data
    self._callback(self.on_message, data)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/binance/websocket/binance_socket_manager.py", line 124, in _callback
    self._handle_exception(e)
    ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/binance/websocket/binance_socket_manager.py", line 130, in _handle_exception
    raise e
  File "/usr/local/lib/python3.13/site-packages/binance/websocket/binance_socket_manager.py", line 121, in _callback
    callback(self, *args)
    ~~~~~~~~^^^^^^^^^^^^^
  File "/bin/BNCTRADE/testapisocketstreambinance", line 15, in message_handler
    print(json_message['stream'])
          ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'stream'

**Comment by alplabin** [comment]
When subscribing to or unsubscribing from a WebSocket stream, a confirmation message is returned as explained [here](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#subscribe-to-a-stream). 
As a result, you may receive two types of messages, one of which does not include the `stream` key. This is why you are encountering an error.

To fix this, update your `message_handler` function as follows: 
```
def message_handler(_, message):
    json_message = json.loads(message)
    if 'stream' in list(json_message.keys()):
        print(json_message['stream'])
```

**Comment by kp0987654321** [comment]
it worked! Thank alplabin
