### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by pngingg** [binance/binance-connector-python#69]
Hi,
I use a proxy to access the api and it crashes with SSL: WRONG_VERSION_NUMBER.
How can I fix it?

code:
```
import logging
from binance.spot import Spot as Client

proxies = { 'https': 'http://192.168.50.60:3213' }

spot_client = Client(base_url='https://api2.binance.com', proxies=proxies)
print(spot_client.ping())
```

output:
```
Traceback (most recent call last):
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/panzhida/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/panzhida/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/panzhida/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/panzhida/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api2.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))
```

**Comment by 2pd** [comment]
Could you please have a try without proxy?

**Comment by pngingg** [comment]
Sorry, This PC cannot access binance without a proxy.

**Comment by 2pd** [comment]
Please look into the proxy server if it allows https connection.

**Comment by aisling11** [comment]
Hi @Tsunami-lj, sorry for late reply, not sure if you've already solved the issue, although if not, check if your proxy server is correctly configured for HTTPS protocol, you can directly using `curl` command with your proxy server and port for testing.

**Comment by aisling11** [comment]
Closing for now, since this doesn't seem to be related with the connector but with the proxy server instead, but feel free to reopen if more investigation is needed.
