### ISSUE TITLE
import failure with undefined symbol: OPENSSL_sk_num

### ISSUE THREAD

**Issue by rollr76518** [binance/binance-connector-python#74]
Before submitting a new issue, please check if a similar issue has already been filed.

### Issue subject
Briefly describe the issue here.

### Expected behaviour
Describe what should happen.
```
pi@raspberrypi:~ $ cat wsTest.py 
from binance.websocket.spot.websocket_client import SpotWebsocketClient as WebsocketClient

def message_handler(message):
    print(message)

ws_client = WebsocketClient()
ws_client.start()

ws_client.mini_ticker(
    symbol='bnbusdt',
    id=1,
    callback=message_handler,
)

# Combine selected streams
ws_client.instant_subscribe(
    stream=['bnbusdt@bookTicker', 'ethusdt@bookTicker'],
    callback=message_handler,
)
```
```
Traceback (most recent call last):
  File "wsTest.py", line 1, in <module>
    from binance.websocket.spot.websocket_client import SpotWebsocketClient as WebsocketClient
  File "/home/pi/.local/lib/python3.6/site-packages/binance/websocket/spot/websocket_client.py", line 1, in <module>
    from binance.websocket.websocket_client import BinanceWebsocketClient
  File "/home/pi/.local/lib/python3.6/site-packages/binance/websocket/websocket_client.py", line 3, in <module>
    from binance.websocket.binance_socket_manager import BinanceSocketManager
  File "/home/pi/.local/lib/python3.6/site-packages/binance/websocket/binance_socket_manager.py", line 5, in <module>
    from twisted.internet import reactor, ssl
  File "/home/pi/.local/lib/python3.6/site-packages/twisted/internet/ssl.py", line 58, in <module>
    from OpenSSL import SSL
  File "/opt/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/miniconda3/lib/python3.6/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/opt/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/pi/.local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/pi/.local/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: OPENSSL_sk_num
```

### Actual behaviour
Describe what happens instead. Please include the complete failure message.

### Steps to reproduce
Provide steps to let us know how we can reproduce this issue.
I install `pip install binance-connector`
and found some warning message
```
 WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/pycparser
  sysconfig: /home/pi/.local/include/python3.6/pycparser
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/pyasn1
  sysconfig: /home/pi/.local/include/python3.6/pyasn1
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/cffi
  sysconfig: /home/pi/.local/include/python3.6/cffi
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/attrs
  sysconfig: /home/pi/.local/include/python3.6/attrs
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/zope.interface
  sysconfig: /home/pi/.local/include/python3.6/zope.interface
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/txaio
  sysconfig: /home/pi/.local/include/python3.6/txaio
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/pyasn1-modules
  sysconfig: /home/pi/.local/include/python3.6/pyasn1-modules
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/incremental
  sysconfig: /home/pi/.local/include/python3.6/incremental
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/hyperlink
  sysconfig: /home/pi/.local/include/python3.6/hyperlink
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/cryptography
  sysconfig: /home/pi/.local/include/python3.6/cryptography
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/constantly
  sysconfig: /home/pi/.local/include/python3.6/constantly
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/Automat
  sysconfig: /home/pi/.local/include/python3.6/Automat
  WARNING: The script automat-visualize is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/Twisted
  sysconfig: /home/pi/.local/include/python3.6/Twisted
  WARNING: The scripts cftp, ckeygen, conch, mailmail, pyhtmlizer, tkconch, trial, twist and twistd are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/service-identity
  sysconfig: /home/pi/.local/include/python3.6/service-identity
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/autobahn
  sysconfig: /home/pi/.local/include/python3.6/autobahn
  WARNING: The scripts wamp and xbrnetwork are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /home/pi/.local/include/python3.6m/binance-connector
  sysconfig: /home/pi/.local/include/python3.6/binance-connector
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/pi/.local/include/python3.6m/UNKNOWN
sysconfig: /home/pi/.local/include/python3.6/UNKNOWN
```

### Environment
Provide any relevant information about your setup, such as:
* Version of binance-connector-python
`binance-connector                 1.3.0`
* Python version
Python 3.6.6
* Operating system
Raspberry Pi OS
Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux

**Comment by rollr76518** [comment]
I don't know why, but I success after run those commends.

pip uninstall pyopenssl
pip uninstall cryptography
pip install pyopenssl
pip install cryptography
